### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by SISTMrL** [NVlabs/FocalFormer3D#1]
Hello, thanks for your wonderful work!!! I'm new to 3D detection task. Could you please provide the config link for each ckpt you have released in your readme. Specifically, I want to know which config files is correspond to the model FocalFormer3D-F with L+C. And the TTA strategy improve the performance greatly, could you please tell me how to use TTA

**Comment by chenyilun95** [comment]
Thanks for your attention. I have uploaded the config link. The TTA can be done by simply changing the test config. I will upload it tomorrow :)

**Comment by chenyilun95** [comment]
@SISTMrL You can found the use of TTA config in README.

**Comment by SISTMrL** [comment]
> @SISTMrL You can found the use of TTA config in README.

thanks!!!
