### ISSUE TITLE
是否遇到过训练卡死的情况

### ISSUE THREAD

**Issue by CX26-CX** [NVlabs/FocalFormer3D#10]
跑训练，会在第一个epoch的第10个batch卡死，但是增大samples_per_gpu就可以跑，这是什么情况

**Comment by chenyilun95** [comment]
没遇到过，你可以试下把workers=0看下哪里卡住

**Comment by CX26-CX** [comment]
![image](https://github.com/NVlabs/FocalFormer3D/assets/71750397/4110d42d-dcbb-4d21-b82e-2b4d1106c28d)
运行bash tools/dist_train.sh projects/configs/focalformer3d/DeformFormer3D_L.py 8，在固定的某个batch后就卡死在focal佛瑞merd.py的outs这个位置：
def forward_pts_train(self,
                          pts_feats,
                          img_feats,
                          gt_bboxes_3d,
                          gt_labels_3d,
                          img_metas,
                          gt_bboxes_ignore=None):
        """Forward function for point cloud branch.

        Args:
            pts_feats (list[torch.Tensor]): Features of point cloud branch
            gt_bboxes_3d (list[:obj:`BaseInstance3DBoxes`]): Ground truth
                boxes for each sample.
            gt_labels_3d (list[torch.Tensor]): Ground truth labels for
                boxes of each sampole
            img_metas (list[dict]): Meta information of samples.
            gt_bboxes_ignore (list[torch.Tensor], optional): Ground truth
                boxes to be ignored. Defaults to None.

        Returns:
            dict: Losses of each branch.
        """
        outs = self.pts_bbox_head(pts_feats, img_feats, img_metas, gt_bboxes_3d=gt_bboxes_3d, gt_labels_3d=gt_labels_3d)
使用的nuscenes-v1.0-mini数据集，用mmdet3d的config跑了一下这个数据集，应该数据处理没问题

**Comment by chenyilun95** [comment]
可能是mini数据的处理问题，你看下输入的tensor比如pts_feats, img_feats这些的shape对不对

**Comment by CX26-CX** [comment]
![image](https://github.com/NVlabs/FocalFormer3D/assets/71750397/5cb7457c-76c6-49fc-9518-0a1f371ea0f4)
麻烦看一下这份处理过后的nuscenes数据集是否有文件缺失

**Comment by chenyilun95** [comment]
data看着没有什么缺失的地方，可以跑跑看下结果是否有报错。

**Comment by CX26-CX** [comment]
![image](https://github.com/NVlabs/FocalFormer3D/assets/71750397/35ecb45a-63f6-4444-9482-bc29ff51e6ba)
定位在这一步会卡死，loss和grad都是正常的，啊好奇怪啊好奇怪

**Comment by chenyilun95** [comment]
这种一般可能是torch版本之类的问题。
