### ISSUE TITLE
请问deformable decoder收敛慢的这两个策略在代码哪里有体现呢

### ISSUE THREAD

**Issue by tengjn** [NVlabs/FocalFormer3D#11]
To address this, we generate noisy queries from ground-truth
objects [18, 77, 78], enabling effective training of the model
from scratch. Additionally, we improve the training process
by excluding matching pairs with a center distance between
the prediction and its GT object exceeding 7 meters.

**Comment by chenyilun95** [comment]
You can locate the places where the two parameters "gt_center_limit" and "add_gt_groups" in focal_decoder.py.

**Comment by tengjn** [comment]
thanks
