### ISSUE TITLE
Why is heatmap_box set False in all configs？

### ISSUE THREAD

**Issue by tengjn** [NVlabs/FocalFormer3D#12]
heatmap_box在工程中全部的cfg全部都是false，这样会导致query_box为None且无法进入self.roi_mlp的处理逻辑~ 请教下原因
https://github.com/NVlabs/FocalFormer3D/blob/71da532da79c918c8d67df8a8b1a4ef9e43204c8/projects/configs/focalformer3d/FocalFormer3D_L.py#L246

**Comment by chenyilun95** [comment]
When comparing the box-type masking strategy for HIP (Table 5), we observed it gets the worse result. in our experiments. Besides, we found that implementing box supervision on the heatmap did not yield benefits.

**Comment by tengjn** [comment]
So, which part of the code corresponds to the "Box-pooling module"

**Comment by chenyilun95** [comment]
We pool the box query feature via RoI Pooling. Check out the option "[roi_feats](https://github.com/NVlabs/FocalFormer3D/blob/71da532da79c918c8d67df8a8b1a4ef9e43204c8/projects/mmdet3d_plugin/models/dense_heads/focal_decoder.py#L84)"
