### ISSUE TITLE
environment problem

### ISSUE THREAD

**Issue by eezhang123** [NVlabs/FocalFormer3D#13]
I follow the install.md step by step, there is something error about

ImportError: /root/mambaforge/envs/lidar/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z27points_in_boxes_cpu_forwardN2at6TensorES0_S0_
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 197538) of binary: /root/mambaforge/envs/lidar/bin/python

Package             Version
------------------- ------------
addict              2.4.0
contourpy           1.1.1
cycler              0.12.1
fonttools           4.47.0
importlib-metadata  7.0.1
importlib-resources 6.1.1
kiwisolver          1.4.5
matplotlib          3.7.4
mmcv-full           1.3.18
mmdet               2.14.0
mmdet3d             0.17.1
mmsegmentation      0.14.1
numpy               1.24.4
opencv-python       4.9.0.80
packaging           23.2
pillow              10.2.0
pip                 23.3.1
platformdirs        4.1.0
prettytable         3.9.0
pycocotools         2.0.7
pyparsing           3.1.1
python-dateutil     2.8.2
PyYAML              6.0.1
setuptools          68.2.2
six                 1.16.0
tensorboard         2.15.1
terminaltables      3.1.10
tomli               2.0.1
torch               1.9.1+cu111
torchaudio          0.9.1
torchvision         0.10.1+cu111
trimesh             2.35.39
typing_extensions   4.9.0
wcwidth             0.2.12
wheel               0.41.2
yapf                0.40.2
zipp                3.17.0

**Comment by chenyilun95** [comment]
It should be mmcv compiling problems. Can you try mmcv-full==1.4.0? Perhaps you need to compile it in your own machine.
You can check my environment https://github.com/NVlabs/FocalFormer3D/issues/8#issuecomment-1754272548
