### ISSUE TITLE
Memory Requirements - Reg

### ISSUE THREAD

**Issue by jyothsna-phd22** [NVlabs/FocalFormer3D#15]
Hello,

I have few questions working with NuScenes dataset.
![image](https://github.com/NVlabs/FocalFormer3D/assets/128205172/b7b0e93d-bc9f-4cbc-857b-ec54210cd77c)

1. For LIDAR-only Nuscenes data excluding radar, camera info, is it enough to download metadata file and lidar blobs only files of each part or do we require to download all the data? 
2. How much RAM and GPU memory is needed to work on 1000 scenes of NuScenes dataset i.e., to train 700 scenes of nuscenes dataset?

**Comment by chenyilun95** [comment]
Hi, Thanks for your interest!
1. The data preparation follows the [mmdet3d doc](https://mmdetection3d.readthedocs.io/en/latest/advanced_guides/datasets/nuscenes.html?highlight=nuscenes#nuscenes-dataset). I haven't tested whether the image-only data preparation works properly yet.
2. The required training memory for LiDAR+Image model should be larger than 24 GB while the LiDAR only model takes ~21 GB. If necessary, you can reduce the batch size to lower the memory usage. The amount of RAM used hasn't been measured.

**Comment by CX26-CX** [comment]
按您的脚本是单卡的GPU显存大小应该大于24G嘛

**Comment by chenyilun95** [comment]
In my impression, it's probably the training of multi-modal model takes 26~27GB, and uni-modal takes ~21GB.

**Comment by CX26-CX** [comment]
模型涉及到spconv库嘛

**Comment by chenyilun95** [comment]
@CX26-CX 对 这是总的训练显存占用。

**Comment by jyothsna-phd22** [comment]
Thank you for your response. Actually I don't have that capable GPU(21 to 27GB) to run on full dataset. Can it be done with google colab/colab pro on full LIDAR-only dataset? If not can you please provide me an alternate solution on how to work on?
