### ISSUE TITLE
Where does the pretrained backbone weights come from

### ISSUE THREAD

**Issue by JOJO173int** [NVlabs/FocalFormer3D#16]
Can you tell me how the r50_fpn_voxel_0075.pth was obtained, thank you

**Comment by JOJO173int** [comment]
Are the r50_fpn_voxel_0075.pth and DeformFormer3D_C_R50/epoch_20.pth equal?

**Comment by chenyilun95** [comment]
No, both single-modal models are trained using this code.

**Comment by JOJO173int** [comment]
> No, both single-modal models are trained using this code.

Thank you for your answer, so what configuration file was used to train this r50_fpn_voxel_0075.pth?

**Comment by chenyilun95** [comment]
The weights come from TransFusion repo, you can refer to [https://github.com/XuyangBai/TransFusion/issues/7](https://github.com/XuyangBai/TransFusion/issues/7)
