### ISSUE TITLE
Nuscenes yaw

### ISSUE THREAD

**Issue by Jayden9912** [NVlabs/FocalFormer3D#17]
Hi.

May I know why we should convert rot to SECOND format while xyz is still in nuscenes coordinate frame?
```
# we need to convert rot to SECOND format.
gt_boxes = np.concatenate([locs, dims, -rots - np.pi / 2], axis=1)
```

**Comment by chenyilun95** [comment]
@Jayden9912 The yaw affects the definition of the coordinates of the box corners, depending on the implementation convention used.

**Comment by chenyilun95** [comment]
You might check out the definitions of different coordinate systems in https://mmdetection3d.readthedocs.io/en/latest/user_guides/coord_sys_tutorial.html.

**Comment by Jayden9912** [comment]
> @Jayden9912 The yaw affects the definition of the coordinates of the box corners, depending on the implementation convention used.

@chenyilun95 Thanks for the reply. Could you clarify more on this? From the nuscenes_converter.py, I think the boxes are in the lidar coordinates_system, which is x to the right, y to the front and z pointing up.
https://github.com/open-mmlab/mmdetection3d/blob/f1107977dfd26155fc1f83779ee6535d2468f449/tools/data_converter/nuscenes_converter.py#L172


 Since the coordinates follow nuscenes lidar coordiante system, why we should convert the yaw to SECOND format, with x pointing front, y pointing left and z pointing up?

**Comment by chenyilun95** [comment]
I'm not entirely certain about the details, but for this implementation, it appears that even within the same coordinate system, the definition of yaw in the code could vary depending on the starting angle.

**Comment by Jayden9912** [comment]
I see, thanks for your reply.

Putting the question on yaw aside, could you point me to any resource on how to use plugin in mmdet3d?

**Comment by chenyilun95** [comment]
You can check out the related library importlib. It's not specifically for mmdet3d in my understanding. [https://github.com/NVlabs/FocalFormer3D/blob/71da532da79c918c8d67df8a8b1a4ef9e43204c8/tools/train.py#L121](https://github.com/NVlabs/FocalFormer3D/blob/71da532da79c918c8d67df8a8b1a4ef9e43204c8/tools/train.py#L121)

**Comment by Jayden9912** [comment]
I see, thanks!
