### ISSUE TITLE
Question aboout step-by-step module refinement

### ISSUE THREAD

**Issue by zyk516** [NVlabs/FocalFormer3D#18]
In the paper, you conduct ablation studies on the step-by-step improvements by each module, presented in Table 6.Despite an improvement in the average recall by over 9 points in Fig. 5, you found little improvement of (b) over (a) in performance after using the multi-stage heatmap encoder to generate the object candidates. 

I think this means model (b)  that uses HIP would cause some wrong FPs. I want to know if this means FocalFormer3D would cause some wrong FPs although FocalFormer3D uses box-level deformable decoder to remove wrong FPs caused by HIP.

Could you please answer my question? Thanks.

**Comment by chenyilun95** [comment]
Thanks for your interest! We have mentioned this point in Sec.3.3 and are thus motivated to introduce another cross-attention module between these candidates. It's a trade-off between Recall & Precision in my understanding. But higher recall is important for autonomous driving system.
