### ISSUE TITLE
Question about multi-stage heatmap encoder

### ISSUE THREAD

**Issue by zyk516** [NVlabs/FocalFormer3D#19]
你好，
对于multi-stage heatmap encoder，我的理解是这样的，每个stage的输入是该stage对应的bev features和上一stage产生的positive mask，将卷积计算用于bev features得到原始的heatmap，之后heatmap与mask相乘，把容易检测到的区域mask掉，最后生成该stage对应的queries
有两个问题想请教下：
（1）每个stage选择topK个prediction用于生成mask，共k个stage，由于mask原始heatmap生成queries的过程中没有可学习的参数，这种multi-stage的方式和one-stage，选择top（k*K）个prediction直接生成queries有何不同
（2）上一stage产生的mask应用到下一stage的bev features是否可行呢
不知道我是否表达清楚了，希望可以交流交流
谢谢

**Comment by chenyilun95** [comment]
Thanks for your interest!
(1) The difference locates their loss on the heatmap between multi-stages. The prior positive predictions of early stages will be ignored and thus the following stages are enforced to learn the hard examples (FN).
(2) I did not conduct this experiments. But I think it might leak messages once you use the convolution with >1x1 kernels.
