### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by SISTMrL** [NVlabs/FocalFormer3D#2]
hello, i didn't found the ckpts of ./work_dirs//DeformFormer3D_C_R50_newbevpool/epoch_20.pth, could you please provide it so that i don't need to train this config: DeformFormer3D_C_R50_newbevpool.py
![image](https://github.com/NVlabs/FocalFormer3D/assets/47938053/e9ff11ad-a352-46ea-bbad-2ad26b51a1c6)

**Comment by chenyilun95** [comment]
Thanks for your attention.The bevpool module is just for faster training speed as bevfusion [1]. I remember that you can directly load it from the checkpoint (the performance is stable to the camera weight). You can report the performance if it gets worse.

I can provide you the weight of the new BEVpool module but it takes some time for training it.

[1] https://github.com/mit-han-lab/bevfusion.
