### ISSUE TITLE
非常棒的工作

### ISSUE THREAD

**Issue by WenxuanLi-whu** [NVlabs/FocalFormer3D#20]

**Comment by WenxuanLi-whu** [comment]
能不能把centerpoint的测试日志发给我一份

**Comment by chenyilun95** [comment]
没懂你说的是哪个图？Table 4？

**Comment by WenxuanLi-whu** [comment]
我就双卡，搞了一点创新点，刷的test集比你低一点，但是消融实验不够，有什么方式可以分析val的结果日志，能给点提示

**Comment by WenxuanLi-whu** [comment]
兄弟，你这个heatmap的dn组件涨了多少点，有测试吗

**Comment by chenyilun95** [comment]
我记得这个之前不添加augmentation fading的时候，应该是~0.5点提升。你可以跑下对比deformformer3d不加这个的结果。

**Comment by rubbish001** [comment]
兄弟，你们那里招人吗？有卡的话可以组个，我感觉我的方法加上你的能刷到70mAP

**Comment by rubbish001** [comment]
可以删除这个帖子了

**Comment by WenxuanLi-whu** [comment]
牛

**Comment by WenxuanLi-whu** [comment]
我刚开始看你的代码，我发现论文中最好的是3阶段，但是那个跳转的代码仅仅是1阶段的heatmap， 能不能把你们那个68.7的配置文件展示出來，我现在想结合你的方法和我的方法在搞一波，而且我测试过query为300的时候训练，精度会下降的，这个配置感觉不对啊

**Comment by chenyilun95** [comment]
提交的模型基本就是给出来的config，multistage_heatmap和num_proposals数目有调整过二阶段和三阶段，之前在榜单上只一次性提交的结果。你这里之前复现的结果是多少？另外可以试下num_proposals=200, multistage_heatmap=2(这个就是三阶段，给出来的模型是二阶段的multistage_heatmap=1速度会快些)。

**Comment by rubbish001** [comment]
兄弟，我没有复现你的算法，我搞了一个算法，精度比你提交的结果低0.7，但是我没有用dn，也没有用多舞台，我现在就是综合起来再搞一波，

**Comment by rubbish001** [comment]
我没有复现你的方法，想跟你交流一下经验，你的代码能力比我强很多，现在在调试你的程序出现one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [4, 128, 505]]的错误，跟了半天不知道哪里被inplace了

**Comment by rubbish001** [comment]
谢谢你的代码，已经能够跑起来了，如果能发一篇paper就好了，我现在一篇paper都没有

**Comment by WenxuanLi-whu** [comment]
兄弟，能发一份训练日志吗，我就这点显卡，基本不会跑别人的模型的，发一份很全的日志到我邮箱或者损失函数图都可以，谢谢啦

**Comment by rubbish001** [comment]
兄弟看看这个训练日志，loss是不是比你的要低一点02/15 11:27:01 - mmengine - INFO - Epoch(train) [14][  50/7724]  lr: 6.2861e-04  eta: 13:17:12  time: 0.8962  data_time: 0.0202  memory: 18203  grad_norm: 0.7641  loss: 1.4626  loss_heatmap: 0.8336  layer_0_loss_cls: 0.0484  layer_0_loss_bbox: 0.1908  layer_1_loss_cls: 0.0451  layer_1_loss_bbox: 0.1821  gt_query_loss_box: 0.1626  gt_query_loss_cls: 0.0000  matched_ious: 0.5858
02/15 11:27:45 - mmengine - INFO - Epoch(train) [14][ 100/7724]  lr: 6.2779e-04  eta: 13:16:27  time: 0.8789  data_time: 0.0121  memory: 18095  grad_norm: 0.7654  loss: 1.4448  loss_heatmap: 0.8258  layer_0_loss_cls: 0.0480  layer_0_loss_bbox: 0.1875  layer_1_loss_cls: 0.0447  layer_1_loss_bbox: 0.1793  gt_query_loss_box: 0.1595  gt_query_loss_cls: 0.0000  matched_ious: 0.5922
02/15 11:28:29 - mmengine - INFO - Epoch(train) [14][ 150/7724]  lr: 6.2697e-04  eta: 13:15:42  time: 0.8752  data_time: 0.0114  memory: 18037  grad_norm: 0.7546  loss: 1.4701  loss_heatmap: 0.8398  layer_0_loss_cls: 0.0481  layer_0_loss_bbox: 0.1904  layer_1_loss_cls: 0.0450  layer_1_loss_bbox: 0.1825  gt_query_loss_box: 0.1642  gt_query_loss_cls: 0.0001  matched_ious: 0.6087
02/15 11:29:13 - mmengine - INFO - Epoch(train) [14][ 200/7724]  lr: 6.2615e-04  eta: 13:14:58  time: 0.8846  data_time: 0.0126  memory: 18073  grad_norm: 0.7702  loss: 1.4969  loss_heatmap: 0.8619  layer_0_loss_cls: 0.0498  layer_0_loss_bbox: 0.1916  layer_1_loss_cls: 0.0465  layer_1_loss_bbox: 0.1830  gt_query_loss_box: 0.1640  gt_query_loss_cls: 0.0001  matched_ious: 0.5778

**Comment by WenxuanLi-whu** [comment]
mAP66.4 NDS	70.9	是多次跑出来的最好值还是随便跑出来的

**Comment by chenyilun95** [comment]
这个挺容易跑出来的，之前最高应该有66.6~左右

**Comment by chenyilun95** [comment]
> 兄弟，能发一份训练日志吗，我就这点显卡，基本不会跑别人的模型的，发一份很全的日志到我邮箱或者损失函数图都可以，谢谢啦

我目前机器上没有nuscenes的数据，暂时没时间跑这个

**Comment by WenxuanLi-whu** [comment]
兄弟，你们那里招人吗，我目前的模型点云在测试服务器上无测试增强比你低0.7%mAP，准备投稿中，如果你看到类似精度的论文，放我一马哈

**Comment by WenxuanLi-whu** [comment]
还有一个问题我没有搞懂，mobilenetv2到底起了啥作用，不要mobilenetv2回降低最少4个点的精度

**Comment by chenyilun95** [comment]
结果应该差不多，mobilenetv2的block只是替代原本的bevfusion的stack convs，速度更快些。

**Comment by WenxuanLi-whu** [comment]
复现你的结果差距很大啊mAP: 0.6507                                                                                                                                                                                                   
mATE: 0.2810
mASE: 0.2602
mAOE: 0.2810
mAVE: 0.2258
mAAE: 0.1901
NDS: 0.7015
Eval time: 115.5s

这个是你最好的200,2，跑出来的效果，你刷那个68.7提交了几次啊

**Comment by chenyilun95** [comment]
这几个模型是一两次提交的结果，提交的模型是需要改成用trainval的数据跑直接提交的。对应的validation的模型结果应该是66.5 mAP，你这里跑的结果明显太低了，是按照两阶段的训练方式吗？训练的时候如果不是8卡，lr应该也得调整。你要不直接邮件发我你的微信吧，这样交流太慢了

**Comment by WenxuanLi-whu** [comment]
哦哦，已经发送我的微信到你的邮箱，我们的训练方式不同，我就是15e+5e退化搞出来的
