### ISSUE TITLE
Environment requirement

### ISSUE THREAD

**Issue by learningfromscratch21** [NVlabs/FocalFormer3D#22]
Hello,

I followed install.md for installing dependencies but mmdet3d version is very old which I am unable to build from source.

I see that you have updated code repo recently. So, why are the versions of mmcv, mmdet3d and mmdet very old. 
I could install mmcv 1.3.18 but I am unable to install mmdet3d version 0.17.1.

Could you please reconfirm the versions?

**Comment by chenyilun95** [comment]
Hi, the installation has been verified if you follow the README. You can refer https://github.com/NVlabs/FocalFormer3D/issues/8 for my environment.yml. 

The codebase borrowed the code from the TransFusion and DeepInteraction repo. The newer version of mmdet3D changed some coordinate transform function. I have no enough time to update it now.
