### ISSUE TITLE
Inplace operation error when training 

### ISSUE THREAD

**Issue by xiazhongyv** [NVlabs/FocalFormer3D#25]
I tried to use DDP to train FocalFomer3D_L under mmdet3d 1.0, but encountered the following error:

```
Traceback (most recent call last):
...
  File ".../mmcv/runner/hooks/optimizer.py", line 64, in after_train_iter
    runner.outputs['loss'].backward()
...
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 128, 702]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

The size of the corresponding FloatTensor should be [samples_per_gpu, 128, k], k is a number between 700 and 1000, and it is different for each forward.

Have you encountered this problem, or can you deduce where this operation occurs?

**Comment by xiazhongyv** [comment]
Fortunately, this operation is relatively easy to position. Error occurs when num_decoder_layers > 1.

https://github.com/NVlabs/FocalFormer3D/blob/master/projects/mmdet3d_plugin/models/dense_heads/focal_decoder.py#L922

```
- query_feat += roi_feat
+ query_feat = query_feat + roi_feat
```

Anyway, thanks for your work. 

There is no problem testing your pth file under mmdet3d 1.0 (Only need to exchange the dx and dy of the model output, and rotate pi/2 for yaw. Compared with the results in your readme, there is only a 0.1mAP loss). I hope I can successfully reproduce your training results under mmdet3d 1.0.

**Comment by xiazhongyv** [comment]
Oh, and I have some other little questions:

I should train DeformFormer3D_L first, right? According to the description of your paper and the corresponding configuration file, the DeformFormer3D_L results are obtained by training with samples_per_gpu=2, 8 V100 GPUs, and initial lr=1e-4. I found that under the above configuration, only about 7G memory is occupied for each GPU. Is this GPU memory usage normal?

If this memory usage is normal, have you tried increasing the batch_size, which would theoretically bring performance improvements?

**Comment by chenyilun95** [comment]
Thanks for the correction. Cool, That's right, you can follow the steps in README. I did not increase the batch_size in my experiments. Let me know your final performance. If that works, would you mind contribute a PR so that I can later update the mmdet version?
