### ISSUE TITLE
db_sampler 

### ISSUE THREAD

**Issue by Wang-pengfei** [NVlabs/FocalFormer3D#26]
Hi, I noticed in your paper that you mentioned not using the db_sampler for the last 5 epochs. Could you please let me know where in the code you determine whether to use the db_sampler or not? Also, I have another question: Does the first stage, DeformFormer3D, also remove the db_sampler in the last 5 epochs?

**Comment by chenyilun95** [comment]
Thanks for interest! You can search "fade_epoch" throughout the code. fade_epoch=15 for DeformFormer3D (20 epoch training) and fade_epoch=1 for FocalFormer3D (6 epoch training).

**Comment by Wang-pengfei** [comment]
Thank you for your nice reply! 
I have another small question: Why is loss not added to every layer in the 6-layer decoder, but rather every 3 layers?

**Comment by chenyilun95** [comment]
I did not ablate this loss design yet. In my view, it won't affect performance too much.
