### ISSUE TITLE
训练过程中的问题

### ISSUE THREAD

**Issue by yizhicainian** [NVlabs/FocalFormer3D#28]
作者你好，我在训练模型过程中epoch设置的20，学习率在训练过程中一直上升，一直到最后两个epoch才下降，这样正常吗，另外问一下训练自己的数据是否需要做类别平衡呢

**Comment by chenyilun95** [comment]
应该是正常的，这里用的是cosine lr。类别均衡的话对训练结果有好处。

**Comment by yizhicainian** [comment]
我训练用来60万帧雷达数据，训练设置20epoch足够吗

**Comment by chenyilun95** [comment]
够，一般数据量多epoch不需要更多。可以把最后16-20epoch都测试下结果。

**Comment by yizhicainian** [comment]
好的，万分感谢
