### ISSUE TITLE
the compile code of bevpool and localattn

### ISSUE THREAD

**Issue by SISTMrL** [NVlabs/FocalFormer3D#3]
Hello, in your project/mmdet3d_plugin/models/utils/ops, there are bevpool and localttn_ops, could you please provide the code to compile these two module? And could you please provide your gcc version? Thanks very much

**Comment by chenyilun95** [comment]
Hi, these two modules will be compiled automatically. The GCC version I used is 9.3.0. You can just install it with anaconda.

**Comment by SISTMrL** [comment]
> Hi, these two modules will be compiled automatically. The GCC version I used is 9.3.0. You can just install it with anaconda.

could you please provide the local_attn.so and bev_pool.so，i can't compile them,

**Comment by SISTMrL** [comment]
> > Hi, these two modules will be compiled automatically. The GCC version I used is 9.3.0. You can just install it with anaconda.
> 
> hello, it's strange to me, i can compile the local_attn.so from the source code that comes from "https://github.com/zzd1992/Image-Local-Attention", but i can't compile the "*.so" file when run the focalformer3d code the problem i was encountered is shown as below. ![image](https://user-images.githubusercontent.com/47938053/260884270-05fafc3b-ad3a-44de-af98-1b86804aa57c.png)
when i convert the gcc version to 4.9 it shows that the gcc version is too old, need >5
> 
> the environment i used is : torch 1.9.0+cu111，the others is same with you. but i want to verify the gnu version you have used
> 
> and the last: could you please provide the local_attn.so and bev_pool.so, if i can use them.

**Comment by SISTMrL** [comment]
> > Hi, these two modules will be compiled automatically. The GCC version I used is 9.3.0. You can just install it with anaconda.
> 
> hello, it's strange to me, i can compile the local_attn.so from the source code that comes from "https://github.com/zzd1992/Image-Local-Attention", but i can't compile the "*.so" file when run the focalformer3d code the problem i was encountered is shown as below ![image](https://user-images.githubusercontent.com/47938053/260884270-05fafc3b-ad3a-44de-af98-1b86804aa57c.png)
> 
> the environment i used is : torch 1.9.0+cu111，the others is same with you
> 
> could you please provide the local_attn.so and bev_pool.so, if i can use them，i can't compile them,

hello, could you please provide the version of your gnu

**Comment by chenyilun95** [comment]
Sure you can download them here:
> https://drive.google.com/drive/folders/1dvQEYPY-2MM4s2AgFzgmG84ggwygxnr-?usp=drive_link

**Comment by SISTMrL** [comment]
> Sure you can download them here:
> 
> > https://drive.google.com/drive/folders/1dvQEYPY-2MM4s2AgFzgmG84ggwygxnr-?usp=drive_link

hello, i put the localattn.so into "models/utils/ops/locatt_ops",  and annotate all the code in "__init.__py" to avoid automatically compiling when i run the code.  when i run the command of "bash tools/dist_train.sh projects/configs/focalformer3d/FocalFormer3D_LC.py 1", the error i was encountered is shown as follow:
![image](https://github.com/NVlabs/FocalFormer3D/assets/47938053/c89a1c70-f7e7-4183-a052-1e8cc7c79328)
and my folder is shown as follows:
![image](https://github.com/NVlabs/FocalFormer3D/assets/47938053/06c387fe-83f8-4c30-a0d7-97957f0c919a)
i just modify the FocalFormer3D_LC.py as follows:
![image](https://github.com/NVlabs/FocalFormer3D/assets/47938053/e41caca4-cb93-4f30-aa94-f95536aadf4e)

**Comment by chenyilun95** [comment]
Does the bev_pool module work? I found you used cuda-8.0 in your path. What's your nvcc version?

**Comment by SISTMrL** [comment]
> Does the bev_pool module work? I found you used cuda-8.0 in your path. What's your nvcc version?

i don't see the bev_pool in the wrong message

i run the nvcc -V, the cuda version is 11.4
![image](https://github.com/NVlabs/FocalFormer3D/assets/47938053/ac29ad74-a25e-437c-9ec0-2bf2c8c32359)

**Comment by chenyilun95** [comment]
Perhaps you can go through the following tutorial to identify the problem. 
> https://pytorch.org/docs/stable/cpp_extension.html
You can find the use of compiling function in locatt_ops/__init__.py.

**Comment by SISTMrL** [comment]
i will have a try

**Comment by russellyq** [comment]
Hi, how to compile it automatically.

**Comment by chenyilun95** [comment]
It should compile automatically on my machine; otherwise, you can compile it yourself.
