### ISSUE TITLE
Low Matched IOUs and No X-Axis Detection During Inference on Custom Point Cloud Data

### ISSUE THREAD

**Issue by who1129** [NVlabs/FocalFormer3D#30]
I made mistake a voxel size!
(deleate the question)

**Comment by chenyilun95** [comment]
Hi, thanks for your interest. It looks like the coordinate system might be wrongly transformed. I suggest you visualize the input point clouds, GT boxes, and PRED boxes using some visualizer like Meshlab and check whether it matches your data.
