### ISSUE TITLE
FocalFormer3D_L_TTA.py

### ISSUE THREAD

**Issue by Terencedu** [NVlabs/FocalFormer3D#31]
Hi,

Thanks for your great work!

Could you please provide the config of "FocalFormer3D_L_TTA.py", because I want to inference with it to make GT annotation labels for my own LiDAR dataset.

I think you have this config already because your results on nuScenes leaderboard are inferenced by LiDAR-only and TTA. If you provide the config, do I test it with "FocalFormer3D_L_ep6_mAP664_NDS709.pth"? I think the ckpt should be the same with "FocalFormer3D_L.py"

Thank you again!

**Comment by chenyilun95** [comment]
Thanks for your interest! The same test-time augmentation is implemented in FocalFormer3D_LC_TTA.py. You can compare it with FocalFormer3D_LC.py using diff.

**Comment by Terencedu** [comment]
Thank you very much! I succeeded using your method.
