### ISSUE TITLE
Changing point_cloud_range for Nuscenes

### ISSUE THREAD

**Issue by adricarda** [NVlabs/FocalFormer3D#33]
Hi, thank you for releasing the code. Results are impressive!

I am trying to retrain your model on Nuscenes by changing the point_cloud_range from [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0] to [-100.0, -100.0, -5.0, 100.0, 100.0, 3.0] (so still a square grid). At the moment however, the model does not seem to work at all, not even below 54 meters. 

I am also using more sweeps to have denser point clouds.

Is there anything else I should change beside point_cloud_range to make predictions further than 54 meters?

Thank you

**Comment by adricarda** [comment]
I found out that I should set up some other parameters to make it work. I am using:

point_cloud_range = [-102.0, -102.0, -5.0, 102.0, 102.0, 3.0]
sparse_shape=[41, 2720, 2720]
grid_size=[2720, 2720, 40]

since voxel size is 0.075 we have 102/0.075 * 2 = 2720

How about post_center_range? I don't really understand what this parameter is.

Thank you.

**Comment by chenyilun95** [comment]
Post_center_range refers to the cropped range of the point clouds after augmentation.

**Comment by adricarda** [comment]
Ok I see, so if I understand correctly I can set it up to be the same as point_cloud_range.
Thank you
