### ISSUE TITLE
Modifying FocalFormer3D_LC.py for Multimodal Learning on a Custom KITTI Dataset

### ISSUE THREAD

**Issue by ckdghks** [NVlabs/FocalFormer3D#36]
Hello, I would like to conduct multimodal learning on a custom dataset in the KITTI dataset format using FocalFormer3D_LC.py, but all the code is based on nuScenes. Could you tell me how to modify FocalFormer3D_LC.py? Thank you.

**Comment by chenyilun95** [comment]
Hi, we have not yet applied FocalFormer3D to the KITTI dataset. You can refer to the MMDet3D library for the modifications needed for the KITTI dataset.
