### ISSUE TITLE
pts_inputs error when I train DeformFormer3D_Waymo_L

### ISSUE THREAD

**Issue by seonhoon1002** [NVlabs/FocalFormer3D#37]
### https://github.com/NVlabs/FocalFormer3D/blob/52e2775194eaa349a59c466e1277c8e7294587f3/projects/mmdet3d_plugin/models/dense_heads/focal_decoder.py#L545

It seems like It should be "pts_inputs[0]" not "pts_inputs[1] "

Is there any special purpose to set '0' which make "View" error because of reshaping "None type"?

**Comment by chenyilun95** [comment]
There is no specific purpose that I recall. The pts_inputs[x] refers to different types of features, where 0 and 1 represent features from different stages.

**Comment by seonhoon1002** [comment]
> There is no specific purpose that I recall. The pts_inputs[x] refers to different types of features, where 0 and 1 represent features from different stages.

When I trained DeformFormer3D_Waymo_L, "new_lidar_feat = pts_inputs[1]" makes "None type error".
So I changed it into pts_inputs[0] and it worked. I think a line of this part need review again. 
Have a nice day
