### ISSUE TITLE
unexpected keyword argument

### ISSUE THREAD

**Issue by SISTMrL** [NVlabs/FocalFormer3D#5]
hello, when i run the bash tools/dist_train.sh projects/configs/focalformer3d/FocalFormer3D_L.py 8, the problem i was encountered is shown as follows:
<img width="688" alt="1692167931920" src="https://github.com/NVlabs/FocalFormer3D/assets/47938053/b12a4869-7bf0-46ee-b5c6-6a9d14e76c7b">

**Comment by chenyilun95** [comment]
Bug fixed. Thanks

**Comment by SISTMrL** [comment]
> Bug fixed. Thanks

thanks for your rapidly response, this config can be trained now. by the way, the local attn is just used in multimodal or camera setting?

**Comment by chenyilun95** [comment]
No. It should be used in all models, and the replacement won't harm the performance if I remember correctly

**Comment by SISTMrL** [comment]
> 

oh, it is strange, why i ran focalformer3d_l or deform3d_l, i didn't encounter the wrong information: https://github.com/NVlabs/FocalFormer3D/issues/3, it can run correctly,

**Comment by SISTMrL** [comment]
> replacement
the replacement means that there is an optional selection to replace local attn?

**Comment by chenyilun95** [comment]
You can set the option: iterbev='bevfusionmb2' that uses mobilenet block instead.

**Comment by SISTMrL** [comment]
> 

change to bevfusionmb2 can have a influence on training speed or performance ?

**Comment by chenyilun95** [comment]
I do not run this setting too much. I remembered performance gets a difference <0.5 points if it gets worse. You can train it yourself, the overall training won't take too much time with 8 GPUs.

**Comment by SISTMrL** [comment]
> I do not run this setting too much. I remembered performance gets a difference <0.5 points if it gets worse. You can train it yourself, the overall training won't take too much time with 8 GPUs.

thanks for your patient reponse, good luck on your academic path
