### ISSUE TITLE
Tracking on Nuscenes 

### ISSUE THREAD

**Issue by afthi** [NVlabs/FocalFormer3D#6]
Hello, thanks for your contribution and the nice repository!!!
I successfully followed your instructions and created the detection results for the Nuscenes dataset by this command
`bash tools/dist_test.sh projects/configs/focalformer3d/FocalFormer3D_L.py ${CHECKPOINT_FILE} 8 --format-only`

However, I would also like to apply tracking on these detection results in order to reproduce your results on the [nuScenes LiDAR Tracking benchmark](https://www.nuscenes.org/tracking?externalData=all&mapData=all&modalities=Lidar).
Could you please share the corresponding code for the tracking part?

**Comment by chenyilun95** [comment]
Thanks for attention!
1. We directly use [SimpleTrack](https://github.com/tusen-ai/SimpleTrack) (2hz) given the detected result.
2. Also note the provided trained model is only trained on the nuScenes train split.
