### ISSUE TITLE
the hip strategy

### ISSUE THREAD

**Issue by SISTMrL** [NVlabs/FocalFormer3D#7]
hello, when i debug your code of "focalformer3d_lc", i didn't found the code related with hip, and i notice that the "acc_masks" is not used in the following code.
![image](https://github.com/NVlabs/FocalFormer3D/assets/47938053/437f7e5b-0df4-4398-aa34-0d5e4a4b4542)
could you please point out the section of hip strategy, thanks!

**Comment by chenyilun95** [comment]
Hi, it is used in the following line to remove positives.
> https://github.com/NVlabs/FocalFormer3D/blob/35542e405ec479f27d414ad3773300eb1280f157/projects/mmdet3d_plugin/models/dense_heads/focal_decoder.py#L666C47-L666C47
